### ISSUE TITLE
NLP Asseter || INTENT_UNIQUE feature not working

### ISSUE THREAD

**Issue by abhinav2019** [codeforequity-at/botium-core#407]
Hi Team,

I am working on Google Dialog Bot and using Botium NLP Asseter Feature.

INTENT and INTENT_CONFIDENCE is working fine for me.
able to identity intent and confidence given to that intent but **not able to verify whether the particular intent is unique or not?**

attaching the Test script as well.

Error :  Expected bot response (on Line 3: #me - hi) "Good day! What can I do for you today?" to match one of "INTENT_UNIQUE"

![nlp_assetion_result](https://user-images.githubusercontent.com/46926479/66455648-fb0e9700-ea88-11e9-957d-e1a001500bf5.PNG)
![test_script_nlp](https://user-images.githubusercontent.com/46926479/66455681-09f54980-ea89-11e9-8819-8ca4d692a939.PNG)

and could you please suggest the use of keyword ENTITIES ? how to use that?

**Comment by codeforequity-at** [comment]
what version of botium box are you using ? Just doing something like this should actually work:

    #bot
    INTENT_UNIQUE

ENTITIES asserter will verify that entities have been resolved, see [docs and examples](https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/17334319/NLP+Asserter+Intents+Entities+Confidence)

**Comment by abhinav2019** [comment]
i m using Botium 1.7.4 version

Tried with the suggestion you provided. It is still not working.

Now it is saying " bot says nothing"

![suggestion](https://user-images.githubusercontent.com/46926479/66476773-0d51fa80-eab4-11e9-8eec-fac88b6cefa1.PNG)
![test_script_nlp](https://user-images.githubusercontent.com/46926479/66476780-0fb45480-eab4-11e9-9260-76fa0728e870.PNG)

**Comment by codeforequity-at** [comment]
This asserter has been added with Botium Box 1.7.5, see [Release Notes](https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/68255745/2019+09+06+Botium+Box+v1.7.5+out+now).

**Comment by abhinav2019** [comment]
Thanks for the info.

will soon upgrade to 1.8 and check this again

**Comment by codeforequity-at** [comment]
2.0 available since today. news on this ?
